const KEY='batana_agency_state';
const state=JSON.parse(localStorage.getItem(KEY)||'{"users":[],"bookings":[],"recovery":[],"visits":0,"session":null}');
state.visits=(state.visits||0)+1; save();
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function app(){return document.getElementById('app')}
function render(view='home'){
 if(view==='home') app().innerHTML=`<section class="container"><div class="hero"><h2>وكالة جامعة البطانة للسفر والسياحة</h2><p>خدمات السفر والحجوزات في مكان واحد.</p></div><div class="grid"><div class="card"><h3>الرحلات</h3><p>استعرض خدمات السفر والحجز.</p></div><div class="card"><h3>الفنادق</h3><p>تابع خيارات الإقامة والحجوزات.</p></div><div class="card"><h3>إدارة الطلبات</h3><p>يمكن للمدير مراجعة الطلبات والموافقة عليها.</p></div></div></section>`;
 if(view==='register') app().innerHTML=formRegister();
 if(view==='login') app().innerHTML=formLogin();
 if(view==='recovery') app().innerHTML=formRecovery();
 if(view==='user') userPanel();
 if(view==='admin') adminPanel();
}
function formRegister(){return `<section class="container"><div class="card form"><h2>إنشاء حساب مستخدم</h2><form id="registerForm"><input name="name" placeholder="الاسم الثلاثي" required><input name="phone" placeholder="رقم الهاتف" required><input type="email" name="email" placeholder="البريد الإلكتروني" required><input type="password" name="password" placeholder="كلمة المرور" required><button class="primary">إنشاء الحساب</button></form></div></section>`}
function formLogin(){return `<section class="container"><div class="card form"><h2>تسجيل الدخول</h2><form id="loginForm"><input name="email" type="email" placeholder="البريد الإلكتروني" required><input name="password" type="password" placeholder="كلمة المرور" required><select name="role"><option value="user">مستخدم</option><option value="admin">مدير</option></select><button class="primary">دخول</button></form><p><button data-view="recovery">نسيت كلمة المرور؟</button></p></div></section>`}
function formRecovery(){return `<section class="container"><div class="card form"><h2>طلب استعادة كلمة المرور</h2><form id="recoveryForm"><input name="name" placeholder="الاسم الثلاثي" required><input name="phone" placeholder="رقم الهاتف" required><input type="email" name="email" placeholder="البريد الإلكتروني" required><button class="primary">إرسال الطلب</button></form><p class="muted">سيتم مراجعة الطلب من المدير. بعد الموافقة يمكن إصدار رمز مؤقت وإرساله عبر قناة WhatsApp Business المهيأة للوكالة.</p></div></section>`}
function userPanel(){const u=state.session;const mine=state.bookings.filter(b=>b.email===u?.email);app().innerHTML=`<section class="container"><div class="card"><h2>لوحة المستخدم</h2><p>مرحباً ${u?.name||''}</p><button class="primary" id="newBooking">إرسال طلب حجز</button> <button data-view="recovery">استعادة كلمة المرور</button></div><div class="card"><h3>طلباتي</h3>${mine.length?`<table><tr><th>الخدمة</th><th>الحالة</th></tr>${mine.map(b=>`<tr><td>${b.service}</td><td>${b.status}</td></tr>`).join('')}</table>`:'لا توجد طلبات بعد.'}</div></section>`;document.getElementById('newBooking').onclick=()=>{const service=prompt('اكتب نوع الخدمة أو الحجز');if(service){state.bookings.push({id:Date.now(),email:u.email,service,status:'قيد المراجعة'});save();userPanel()}}}
function adminPanel(){if(state.session?.role!=='admin'){app().innerHTML=`<section class="container"><div class="card"><h2>دخول المدير</h2><p>سجّل الدخول بحساب مدير من صفحة تسجيل الدخول.</p></div></section>`;return}app().innerHTML=`<section class="container"><div class="grid"><div class="card"><h3>الزوار</h3><div class="stat">${state.visits}</div></div><div class="card"><h3>المستخدمون</h3><div class="stat">${state.users.length}</div></div><div class="card"><h3>الحجوزات</h3><div class="stat">${state.bookings.length}</div></div><div class="card"><h3>طلبات الاستعادة</h3><div class="stat">${state.recovery.length}</div></div></div><div class="card"><h2>الحجوزات</h2>${bookingTable()}</div><div class="card"><h2>طلبات استعادة كلمة المرور</h2>${recoveryTable()}</div><div class="card"><h2>المستخدمون</h2>${userTable()}</div></section>`}
function bookingTable(){return state.bookings.length?`<table><tr><th>المستخدم</th><th>الخدمة</th><th>الحالة</th><th>إجراء</th></tr>${state.bookings.map((b,i)=>`<tr><td>${b.email}</td><td>${b.service}</td><td>${b.status}</td><td><button class="success" onclick="bookingStatus(${i},'مقبول')">موافقة</button> <button class="danger" onclick="bookingStatus(${i},'مرفوض')">رفض</button></td></tr>`).join('')}</table>`:'لا توجد حجوزات.'}
function recoveryTable(){return state.recovery.length?`<table><tr><th>الاسم</th><th>الهاتف</th><th>البريد</th><th>الحالة</th><th>إجراء</th></tr>${state.recovery.map((r,i)=>`<tr><td>${r.name}</td><td>${r.phone}</td><td>${r.email}</td><td>${r.status}</td><td><button class="success" onclick="approveRecovery(${i})">موافقة</button></td></tr>`).join('')}</table>`:'لا توجد طلبات.'}
function userTable(){return state.users.length?`<table><tr><th>الاسم</th><th>الهاتف</th><th>البريد</th><th>الدور</th></tr>${state.users.map(u=>`<tr><td>${u.name}</td><td>${u.phone}</td><td>${u.email}</td><td>${u.role}</td></tr>`).join('')}</table>`:'لا يوجد مستخدمون.'}
function bookingStatus(i,status){state.bookings[i].status=status;save();adminPanel()}
function approveRecovery(i){const r=state.recovery[i];r.status='مقبول';r.tempPassword='TEMP-'+Math.random().toString(36).slice(2,8).toUpperCase();save();const text=encodeURIComponent(`وكالة جامعة البطانة للسفر والسياحة\nتمت الموافقة على طلب استعادة الحساب. كلمة المرور المؤقتة: ${r.tempPassword}`);window.open(`https://wa.me/${normalizePhone(r.phone)}?text=${text}`,'_blank');adminPanel()}
function normalizePhone(phone){let p=String(phone).replace(/\D/g,'');if(p.startsWith('0'))p='249'+p.slice(1);return p}
document.addEventListener('click',e=>{const v=e.target.dataset.view;if(v)render(v)});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));if(f.id==='registerForm'){if(state.users.some(u=>u.email===d.email))return alert('البريد مستخدم بالفعل');state.users.push({...d,role:'user'});save();alert('تم إنشاء الحساب');render('login')}else if(f.id==='loginForm'){const u=state.users.find(x=>x.email===d.email&&x.password===d.password&&x.role===d.role);if(!u&&d.role==='admin'&&d.email==='admin@batana.local'&&d.password==='ChangeMe123!'){state.session={name:'مدير النظام',email:d.email,role:'admin'};save();adminPanel();return}if(!u)return alert('بيانات الدخول غير صحيحة');state.session=u;save();render('user')}else if(f.id==='recoveryForm'){state.recovery.push({...d,status:'قيد المراجعة',createdAt:new Date().toISOString()});save();alert('تم إرسال طلب الاستعادة إلى المدير');render('login')}});
render();
